### PR TITLE
CU-8694vxbkh: Medcat v1.12 support

### PR DESCRIPTION
**Pull request by mart-r**
Remove use of deprecated method.

TODO:

- [x] Update requirements to `medcat==1.12` (waiting on MedCAT release)

### CODE REVIEW

**Review by tomolopolis — APPROVED** [review]
lgtm

**Comment by mart-r** [comment]
NOTE:
There is an issue with this PR, regarding `medcat/evaluate_mct_export/mct_analysis.py` using the `medcat.utils.meta_cat.data_utils.encode_category_values` method (the signature of which was changed in MedCAT 1.12 due to PR 419).
Refer to CU task:
https://app.clickup.com/t/8695vz088

**Comment by shubham-s-agarwal** [comment]
Added the change for below

> NOTE: There is an issue with this PR, regarding `medcat/evaluate_mct_export/mct_analysis.py` using the `medcat.utils.meta_cat.data_utils.encode_category_values` method (the signature of which was changed in MedCAT 1.12 due to PR 419). Refer to CU task: https://app.clickup.com/t/8695vz088

**Review by tomolopolis — APPROVED** [review]
lgtm

**Pull request merged**
